version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: property_prices
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Mounting the PostgreSQL data directory to the host
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mounting the init script

